name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: bun install
        run: |
          bun install

      - name: bun test
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bun run package
          bun run lint
          bun x tsc
          bun test
